import { NextRequest, NextResponse } from "next/server";
import { prisma } from "@/lib/prisma";
import { logOperation } from "@/lib/ops-log";

export async function GET() {
  try {
    let settings = await prisma.companySettings.findUnique({ where: { id: 1 } });
    if (!settings) {
      settings = await prisma.companySettings.create({
        data: {
          id: 1,
          companyName: "Sahara Global Industrial Chemicals & Resins (SGICR)",
          pdfHeaderSpacePx: 72,
          pdfFooterSpacePx: 56,
          quoteNumberPrefix: "QT",
          orderNumberPrefix: "SO",
          invoiceNumberPrefix: "INV",
          deliveryNumberPrefix: "DL",
          purchaseOrderNumberPrefix: "PO",
          journalNumberPrefix: "JE",
          payrollNumberPrefix: "PAY",
        },
      });
    }

    return NextResponse.json(settings);
  } catch (error) {
    return NextResponse.json({ error: "Failed to fetch company settings" }, { status: 500 });
  }
}

export async function PUT(req: NextRequest) {
  try {
    const data = await req.json();
    const headerSpace = Number(data.pdfHeaderSpacePx ?? 72);
    const footerSpace = Number(data.pdfFooterSpacePx ?? 56);
    const cleanPrefix = (value: unknown, fallback: string) => {
      const base = String(value ?? fallback).trim().toUpperCase();
      return base.length > 0 ? base.slice(0, 12) : fallback;
    };
    const normalizeSeq = (value: unknown) => {
      const n = Number(value);
      return Number.isFinite(n) && n > 0 ? Math.floor(n) : 1;
    };
    const normalizedData = {
      ...data,
      companyName: data.companyName ?? "Sahara Global Industrial Chemicals & Resins (SGICR)",
      pdfHeaderSpacePx: Number.isFinite(headerSpace) ? Math.max(0, headerSpace) : 72,
      pdfFooterSpacePx: Number.isFinite(footerSpace) ? Math.max(0, footerSpace) : 56,
      pdfLetterheadUrl: data.pdfLetterheadUrl ? String(data.pdfLetterheadUrl) : null,
      pdfSignatureUrl: data.pdfSignatureUrl ? String(data.pdfSignatureUrl) : null,
      pdfStampUrl: data.pdfStampUrl ? String(data.pdfStampUrl) : null,
      printFooterEn: data.printFooterEn ? String(data.printFooterEn) : "Generated by ERP SGICR",
      printFooterFr: data.printFooterFr ? String(data.printFooterFr) : "Genere par ERP SGICR",
      printTermsEn: data.printTermsEn ? String(data.printTermsEn) : null,
      printTermsFr: data.printTermsFr ? String(data.printTermsFr) : null,
      showSignatureOnPrint: data.showSignatureOnPrint !== false,
      showStampOnPrint: data.showStampOnPrint !== false,
      quoteTemplateUrl: data.quoteTemplateUrl ? String(data.quoteTemplateUrl) : null,
      orderTemplateUrl: data.orderTemplateUrl ? String(data.orderTemplateUrl) : null,
      invoiceTemplateUrl: data.invoiceTemplateUrl ? String(data.invoiceTemplateUrl) : null,
      deliveryTemplateUrl: data.deliveryTemplateUrl ? String(data.deliveryTemplateUrl) : null,
      purchaseOrderTemplateUrl: data.purchaseOrderTemplateUrl ? String(data.purchaseOrderTemplateUrl) : null,
      payrollTemplateUrl: data.payrollTemplateUrl ? String(data.payrollTemplateUrl) : null,
      journalTemplateUrl: data.journalTemplateUrl ? String(data.journalTemplateUrl) : null,
      quoteNumberPrefix: cleanPrefix(data.quoteNumberPrefix, "QT"),
      orderNumberPrefix: cleanPrefix(data.orderNumberPrefix, "SO"),
      invoiceNumberPrefix: cleanPrefix(data.invoiceNumberPrefix, "INV"),
      deliveryNumberPrefix: cleanPrefix(data.deliveryNumberPrefix, "DL"),
      purchaseOrderNumberPrefix: cleanPrefix(data.purchaseOrderNumberPrefix, "PO"),
      journalNumberPrefix: cleanPrefix(data.journalNumberPrefix, "JE"),
      payrollNumberPrefix: cleanPrefix(data.payrollNumberPrefix, "PAY"),
      quoteSequence: normalizeSeq(data.quoteSequence),
      orderSequence: normalizeSeq(data.orderSequence),
      invoiceSequence: normalizeSeq(data.invoiceSequence),
      deliverySequence: normalizeSeq(data.deliverySequence),
      purchaseOrderSequence: normalizeSeq(data.purchaseOrderSequence),
      journalSequence: normalizeSeq(data.journalSequence),
      payrollSequence: normalizeSeq(data.payrollSequence),
    };

    const settings = await prisma.companySettings.upsert({
      where: { id: 1 },
      update: normalizedData,
      create: {
        id: 1,
        ...normalizedData,
      },
    });

    await logOperation({
      action: "SETTINGS_UPDATED",
      entityType: "CompanySettings",
      entityId: settings.id,
      details: `Company profile updated for ${settings.companyName}`,
    });

    return NextResponse.json(settings);
  } catch (error) {
    return NextResponse.json({ error: "Failed to update company settings" }, { status: 500 });
  }
}
