"use client";

import Link from "next/link";
import { useEffect, useState } from "react";
import NavOrderSection from "./NavOrderSection";

type CompanySettings = {
  companyName: string;
  companyEmail: string;
  companyPhone: string;
  address: string;
  ice: string;
  ifCode: string;
  rc: string;
  cnss: string;
  patente: string;
  vatRate: number;
  currency: string;
  language: string;
  fiscalYearStart: number;
  pdfLetterheadUrl: string;
  pdfSignatureUrl: string;
  pdfStampUrl: string;
  quoteTemplateUrl: string;
  orderTemplateUrl: string;
  invoiceTemplateUrl: string;
  deliveryTemplateUrl: string;
  purchaseOrderTemplateUrl: string;
  payrollTemplateUrl: string;
  journalTemplateUrl: string;
  printFooterEn: string;
  printFooterFr: string;
  printTermsEn: string;
  printTermsFr: string;
  showSignatureOnPrint: boolean;
  showStampOnPrint: boolean;
  pdfHeaderSpacePx: number;
  pdfFooterSpacePx: number;
  quoteNumberPrefix: string;
  orderNumberPrefix: string;
  invoiceNumberPrefix: string;
  deliveryNumberPrefix: string;
  purchaseOrderNumberPrefix: string;
  journalNumberPrefix: string;
  payrollNumberPrefix: string;
  quoteSequence: number;
  orderSequence: number;
  invoiceSequence: number;
  deliverySequence: number;
  purchaseOrderSequence: number;
  journalSequence: number;
  payrollSequence: number;
};

const defaultSettings: CompanySettings = {
  companyName: "Sahara Global Industrial Chemicals & Resins (SGICR)",
  companyEmail: "",
  companyPhone: "",
  address: "",
  ice: "",
  ifCode: "",
  rc: "",
  cnss: "",
  patente: "",
  vatRate: 20,
  currency: "MAD",
  language: "en",
  fiscalYearStart: 1,
  pdfLetterheadUrl: "",
  pdfSignatureUrl: "",
  pdfStampUrl: "",
  quoteTemplateUrl: "",
  orderTemplateUrl: "",
  invoiceTemplateUrl: "",
  deliveryTemplateUrl: "",
  purchaseOrderTemplateUrl: "",
  payrollTemplateUrl: "",
  journalTemplateUrl: "",
  printFooterEn: "Generated by ERP SGICR",
  printFooterFr: "Genere par ERP SGICR",
  printTermsEn: "",
  printTermsFr: "",
  showSignatureOnPrint: true,
  showStampOnPrint: true,
  pdfHeaderSpacePx: 140,
  pdfFooterSpacePx: 56,
  quoteNumberPrefix: "QT",
  orderNumberPrefix: "SO",
  invoiceNumberPrefix: "INV",
  deliveryNumberPrefix: "DL",
  purchaseOrderNumberPrefix: "PO",
  journalNumberPrefix: "JE",
  payrollNumberPrefix: "PAY",
  quoteSequence: 1,
  orderSequence: 1,
  invoiceSequence: 1,
  deliverySequence: 1,
  purchaseOrderSequence: 1,
  journalSequence: 1,
  payrollSequence: 1,
};

export default function SettingsPage() {
  const [form, setForm] = useState<CompanySettings>(defaultSettings);
  const [loading, setLoading] = useState(true);
  const [saving, setSaving] = useState(false);
  const [uploadingAsset, setUploadingAsset] = useState<
    ""
    | "letterhead"
    | "signature"
    | "stamp"
    | "template_quote"
    | "template_order"
    | "template_invoice"
    | "template_delivery"
    | "template_purchase_order"
    | "template_payroll"
    | "template_journal"
  >("");
  const [message, setMessage] = useState("");
  const [error, setError] = useState("");

  useEffect(() => {
    const loadSettings = async () => {
      try {
        const res = await fetch("/api/settings/company");
        if (!res.ok) {
          throw new Error("Failed to load settings");
        }

        const data = await res.json();
        setForm({
          companyName: data.companyName ?? "",
          companyEmail: data.companyEmail ?? "",
          companyPhone: data.companyPhone ?? "",
          address: data.address ?? "",
          ice: data.ice ?? "",
          ifCode: data.ifCode ?? "",
          rc: data.rc ?? "",
          cnss: data.cnss ?? "",
          patente: data.patente ?? "",
          vatRate: Number(data.vatRate ?? 20),
          currency: data.currency ?? "MAD",
          language: data.language ?? "en",
          fiscalYearStart: Number(data.fiscalYearStart ?? 1),
          pdfLetterheadUrl: data.pdfLetterheadUrl ?? "",
          pdfSignatureUrl: data.pdfSignatureUrl ?? "",
          pdfStampUrl: data.pdfStampUrl ?? "",
          quoteTemplateUrl: data.quoteTemplateUrl ?? "",
          orderTemplateUrl: data.orderTemplateUrl ?? "",
          invoiceTemplateUrl: data.invoiceTemplateUrl ?? "",
          deliveryTemplateUrl: data.deliveryTemplateUrl ?? "",
          purchaseOrderTemplateUrl: data.purchaseOrderTemplateUrl ?? "",
          payrollTemplateUrl: data.payrollTemplateUrl ?? "",
          journalTemplateUrl: data.journalTemplateUrl ?? "",
          printFooterEn: data.printFooterEn ?? "Generated by ERP SGICR",
          printFooterFr: data.printFooterFr ?? "Genere par ERP SGICR",
          printTermsEn: data.printTermsEn ?? "",
          printTermsFr: data.printTermsFr ?? "",
          showSignatureOnPrint: data.showSignatureOnPrint !== false,
          showStampOnPrint: data.showStampOnPrint !== false,
          pdfHeaderSpacePx: Number(data.pdfHeaderSpacePx ?? 140),
          pdfFooterSpacePx: Number(data.pdfFooterSpacePx ?? 56),
          quoteNumberPrefix: data.quoteNumberPrefix ?? "QT",
          orderNumberPrefix: data.orderNumberPrefix ?? "SO",
          invoiceNumberPrefix: data.invoiceNumberPrefix ?? "INV",
          deliveryNumberPrefix: data.deliveryNumberPrefix ?? "DL",
          purchaseOrderNumberPrefix: data.purchaseOrderNumberPrefix ?? "PO",
          journalNumberPrefix: data.journalNumberPrefix ?? "JE",
          payrollNumberPrefix: data.payrollNumberPrefix ?? "PAY",
          quoteSequence: Number(data.quoteSequence ?? 1),
          orderSequence: Number(data.orderSequence ?? 1),
          invoiceSequence: Number(data.invoiceSequence ?? 1),
          deliverySequence: Number(data.deliverySequence ?? 1),
          purchaseOrderSequence: Number(data.purchaseOrderSequence ?? 1),
          journalSequence: Number(data.journalSequence ?? 1),
          payrollSequence: Number(data.payrollSequence ?? 1),
        });
      } catch (e) {
        setError(e instanceof Error ? e.message : "Could not load settings");
      } finally {
        setLoading(false);
      }
    };

    loadSettings();
  }, []);

  const setValue = <K extends keyof CompanySettings>(key: K, value: CompanySettings[K]) => {
    setForm((prev) => ({ ...prev, [key]: value }));
  };

  const uploadAsset = async (
    asset:
      | "letterhead"
      | "signature"
      | "stamp"
      | "template_quote"
      | "template_order"
      | "template_invoice"
      | "template_delivery"
      | "template_purchase_order"
      | "template_payroll"
      | "template_journal",
    file: File
  ) => {
    setUploadingAsset(asset);
    setError("");
    setMessage("");
    try {
      const payload = new FormData();
      payload.append("file", file);
      const res = await fetch(`/api/settings/company/upload?asset=${asset}`, {
        method: "POST",
        body: payload,
      });

      if (!res.ok) {
        const data = await res.json().catch(() => ({ error: "Upload failed" }));
        throw new Error(data.error || "Upload failed");
      }

      const data = await res.json();
      if (asset === "letterhead") setValue("pdfLetterheadUrl", data.url || "");
      if (asset === "signature") setValue("pdfSignatureUrl", data.url || "");
      if (asset === "stamp") setValue("pdfStampUrl", data.url || "");
      if (asset === "template_quote") setValue("quoteTemplateUrl", data.url || "");
      if (asset === "template_order") setValue("orderTemplateUrl", data.url || "");
      if (asset === "template_invoice") setValue("invoiceTemplateUrl", data.url || "");
      if (asset === "template_delivery") setValue("deliveryTemplateUrl", data.url || "");
      if (asset === "template_purchase_order") setValue("purchaseOrderTemplateUrl", data.url || "");
      if (asset === "template_payroll") setValue("payrollTemplateUrl", data.url || "");
      if (asset === "template_journal") setValue("journalTemplateUrl", data.url || "");
      setMessage(`${asset} image uploaded successfully.`);
    } catch (e) {
      setError(e instanceof Error ? e.message : "Upload failed");
    } finally {
      setUploadingAsset("");
    }
  };

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setSaving(true);
    setMessage("");
    setError("");

    try {
      const res = await fetch("/api/settings/company", {
        method: "PUT",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify(form),
      });

      if (!res.ok) {
        const data = await res.json().catch(() => ({ error: "Failed to save settings" }));
        throw new Error(data.error || "Failed to save settings");
      }

      setMessage("Settings saved successfully.");
    } catch (e) {
      setError(e instanceof Error ? e.message : "Could not save settings");
    } finally {
      setSaving(false);
    }
  };

  return (
    <main className="space-y-6">
      <section className="card">
        <div className="page-header mb-0">
          <div>
            <h1 className="page-title">System Settings</h1>
            <p className="page-subtitle">
              Configure company profile, fiscal defaults, and compliance identifiers.
            </p>
          </div>
        </div>
      </section>

      <section className="grid gap-4 lg:grid-cols-2">
        <div className="card space-y-3">
          <h2 className="text-lg font-semibold text-white">Access Control</h2>
          <p className="text-sm text-slate-400">
            Manage admin, manager, and staff accounts from the dedicated user access panel.
          </p>
          <div>
            <Link href="/settings/users" className="btn-primary btn-sm">
              Open User Access
            </Link>
          </div>
        </div>

        <div className="card space-y-3">
          <h2 className="text-lg font-semibold text-white">Data Tools</h2>
          <p className="text-sm text-slate-400">
            Import and export core master data through the Excel data exchange workspace.
          </p>
          <div>
            <Link href="/settings/data-exchange" className="btn-secondary btn-sm">
              Open Data Exchange
            </Link>
          </div>
        </div>
      </section>

      <form onSubmit={handleSubmit} className="space-y-6">
        <section className="grid gap-6 lg:grid-cols-2">
          <div className="card space-y-4">
            <h2 className="text-lg font-semibold text-white">Company Profile</h2>
            <div className="form-group">
              <label className="label">Company Name</label>
              <input
                className="input"
                value={form.companyName}
                onChange={(e) => setValue("companyName", e.target.value)}
                required
              />
            </div>
            <div className="form-group">
              <label className="label">Email</label>
              <input
                type="email"
                className="input"
                value={form.companyEmail}
                onChange={(e) => setValue("companyEmail", e.target.value)}
              />
            </div>
            <div className="form-group">
              <label className="label">Phone</label>
              <input
                className="input"
                value={form.companyPhone}
                onChange={(e) => setValue("companyPhone", e.target.value)}
              />
            </div>
            <div className="form-group">
              <label className="label">Address</label>
              <textarea
                className="input min-h-24"
                value={form.address}
                onChange={(e) => setValue("address", e.target.value)}
              />
            </div>
          </div>

          <div className="card space-y-4">
            <h2 className="text-lg font-semibold text-white">Fiscal Defaults</h2>
            <div className="grid gap-4 sm:grid-cols-2">
              <div className="form-group">
                <label className="label">VAT Rate (%)</label>
                <input
                  type="number"
                  min="0"
                  step="0.1"
                  className="input"
                  value={form.vatRate}
                  onChange={(e) => setValue("vatRate", Number(e.target.value || 0))}
                />
              </div>
              <div className="form-group">
                <label className="label">Fiscal Year Start (month)</label>
                <input
                  type="number"
                  min="1"
                  max="12"
                  className="input"
                  value={form.fiscalYearStart}
                  onChange={(e) => setValue("fiscalYearStart", Number(e.target.value || 1))}
                />
              </div>
              <div className="form-group">
                <label className="label">Currency</label>
                <select
                  className="input"
                  value={form.currency}
                  onChange={(e) => setValue("currency", e.target.value)}
                >
                  <option value="MAD">MAD</option>
                  <option value="EUR">EUR</option>
                  <option value="USD">USD</option>
                </select>
              </div>
              <div className="form-group">
                <label className="label">Language</label>
                <select
                  className="input"
                  value={form.language}
                  onChange={(e) => setValue("language", e.target.value)}
                >
                  <option value="en">English</option>
                  <option value="fr">French</option>
                  <option value="ar">Arabic</option>
                </select>
              </div>
            </div>
          </div>
        </section>

        <section className="card space-y-4">
          <h2 className="text-lg font-semibold text-white">Compliance Identifiers</h2>
          <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">
            <div className="form-group">
              <label className="label">ICE</label>
              <input className="input" value={form.ice} onChange={(e) => setValue("ice", e.target.value)} />
            </div>
            <div className="form-group">
              <label className="label">IF</label>
              <input className="input" value={form.ifCode} onChange={(e) => setValue("ifCode", e.target.value)} />
            </div>
            <div className="form-group">
              <label className="label">RC</label>
              <input className="input" value={form.rc} onChange={(e) => setValue("rc", e.target.value)} />
            </div>
            <div className="form-group">
              <label className="label">CNSS</label>
              <input className="input" value={form.cnss} onChange={(e) => setValue("cnss", e.target.value)} />
            </div>
            <div className="form-group">
              <label className="label">Patente</label>
              <input
                className="input"
                value={form.patente}
                onChange={(e) => setValue("patente", e.target.value)}
              />
            </div>
          </div>
        </section>

        <section className="card space-y-4">
          <h2 className="text-lg font-semibold text-white">PDF Branding & Layout</h2>
          <p className="text-sm text-slate-400">
            Configure letterhead and printable header/footer spacing for all ERP document PDFs.
          </p>
          <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">
            <div className="form-group sm:col-span-2 lg:col-span-3">
              <label className="label">Letterhead Image (Upload)</label>
              <input type="file" accept="image/png,image/jpeg,image/webp" className="input" onChange={(e) => { const f = e.target.files?.[0]; if (f) uploadAsset("letterhead", f); }} />
              <div className="text-xs text-slate-400 mt-1">Current: {form.pdfLetterheadUrl || "Not uploaded"}</div>
            </div>
            <div className="form-group sm:col-span-2 lg:col-span-3">
              <label className="label">Authorized Signature Image (Upload)</label>
              <input type="file" accept="image/png,image/jpeg,image/webp" className="input" onChange={(e) => { const f = e.target.files?.[0]; if (f) uploadAsset("signature", f); }} />
              <div className="text-xs text-slate-400 mt-1">Current: {form.pdfSignatureUrl || "Not uploaded"}</div>
            </div>
            <div className="form-group sm:col-span-2 lg:col-span-3">
              <label className="label">Company Stamp Image (Upload)</label>
              <input type="file" accept="image/png,image/jpeg,image/webp" className="input" onChange={(e) => { const f = e.target.files?.[0]; if (f) uploadAsset("stamp", f); }} />
              <div className="text-xs text-slate-400 mt-1">Current: {form.pdfStampUrl || "Not uploaded"}</div>
            </div>
            <div className="form-group">
              <label className="label">Header Space (px)</label>
              <input
                type="number"
                min="0"
                max="400"
                className="input"
                value={form.pdfHeaderSpacePx}
                onChange={(e) => setValue("pdfHeaderSpacePx", Number(e.target.value || 0))}
              />
            </div>
            <div className="form-group">
              <label className="label">Footer Space (px)</label>
              <input
                type="number"
                min="0"
                max="400"
                className="input"
                value={form.pdfFooterSpacePx}
                onChange={(e) => setValue("pdfFooterSpacePx", Number(e.target.value || 0))}
              />
            </div>
          </div>
        </section>

        <section className="card space-y-4">
          <h2 className="text-lg font-semibold text-white">Document Format Controls</h2>
          <p className="text-sm text-slate-400">Control footer text, legal terms, and print signatures for all documents.</p>
          <div className="grid gap-4 sm:grid-cols-2">
            <div className="form-group">
              <label className="label">Print Footer (English)</label>
              <input className="input" value={form.printFooterEn} onChange={(e) => setValue("printFooterEn", e.target.value)} />
            </div>
            <div className="form-group">
              <label className="label">Print Footer (French)</label>
              <input className="input" value={form.printFooterFr} onChange={(e) => setValue("printFooterFr", e.target.value)} />
            </div>
            <div className="form-group sm:col-span-2">
              <label className="label">Default Terms (English)</label>
              <textarea className="input min-h-24" value={form.printTermsEn} onChange={(e) => setValue("printTermsEn", e.target.value)} placeholder="Payment terms, validity, legal clauses..." />
            </div>
            <div className="form-group sm:col-span-2">
              <label className="label">Default Terms (French)</label>
              <textarea className="input min-h-24" value={form.printTermsFr} onChange={(e) => setValue("printTermsFr", e.target.value)} placeholder="Conditions de paiement, validite, clauses..." />
            </div>
            <label className="inline-flex items-center gap-2 text-sm text-slate-200">
              <input type="checkbox" checked={form.showSignatureOnPrint} onChange={(e) => setValue("showSignatureOnPrint", e.target.checked)} />
              Show authorized signature on prints
            </label>
            <label className="inline-flex items-center gap-2 text-sm text-slate-200">
              <input type="checkbox" checked={form.showStampOnPrint} onChange={(e) => setValue("showStampOnPrint", e.target.checked)} />
              Show company stamp on prints
            </label>
          </div>
        </section>

        <section className="card space-y-4">
          <h2 className="text-lg font-semibold text-white">Per-Document Templates</h2>
          <p className="text-sm text-slate-400">Upload background templates per document. If empty, system uses global letterhead.</p>
          <div className="text-xs text-slate-400 bg-slate-800/40 border border-slate-700/50 rounded-md px-3 py-2">
            Accepted format: <strong>PNG, JPG/JPEG, WEBP</strong> only (max 8MB).<br />
            Recommended for clean print: <strong>A4 portrait ratio</strong> (for example 2480x3508 px at 300 DPI), transparent or very light background.
          </div>
          <div className="grid gap-4 sm:grid-cols-2">
            <div className="form-group"><label className="label">Quote Template</label><input type="file" accept="image/png,image/jpeg,image/webp" className="input" onChange={(e) => { const f = e.target.files?.[0]; if (f) uploadAsset("template_quote", f); }} /><div className="text-xs text-slate-400 mt-1">Current: {form.quoteTemplateUrl || "Not uploaded"}</div></div>
            <div className="form-group"><label className="label">Sales Order Template</label><input type="file" accept="image/png,image/jpeg,image/webp" className="input" onChange={(e) => { const f = e.target.files?.[0]; if (f) uploadAsset("template_order", f); }} /><div className="text-xs text-slate-400 mt-1">Current: {form.orderTemplateUrl || "Not uploaded"}</div></div>
            <div className="form-group"><label className="label">Invoice Template</label><input type="file" accept="image/png,image/jpeg,image/webp" className="input" onChange={(e) => { const f = e.target.files?.[0]; if (f) uploadAsset("template_invoice", f); }} /><div className="text-xs text-slate-400 mt-1">Current: {form.invoiceTemplateUrl || "Not uploaded"}</div></div>
            <div className="form-group"><label className="label">Delivery Note Template</label><input type="file" accept="image/png,image/jpeg,image/webp" className="input" onChange={(e) => { const f = e.target.files?.[0]; if (f) uploadAsset("template_delivery", f); }} /><div className="text-xs text-slate-400 mt-1">Current: {form.deliveryTemplateUrl || "Not uploaded"}</div></div>
            <div className="form-group"><label className="label">Purchase Order Template</label><input type="file" accept="image/png,image/jpeg,image/webp" className="input" onChange={(e) => { const f = e.target.files?.[0]; if (f) uploadAsset("template_purchase_order", f); }} /><div className="text-xs text-slate-400 mt-1">Current: {form.purchaseOrderTemplateUrl || "Not uploaded"}</div></div>
            <div className="form-group"><label className="label">Payroll Template</label><input type="file" accept="image/png,image/jpeg,image/webp" className="input" onChange={(e) => { const f = e.target.files?.[0]; if (f) uploadAsset("template_payroll", f); }} /><div className="text-xs text-slate-400 mt-1">Current: {form.payrollTemplateUrl || "Not uploaded"}</div></div>
            <div className="form-group sm:col-span-2"><label className="label">Journal Entry Template</label><input type="file" accept="image/png,image/jpeg,image/webp" className="input" onChange={(e) => { const f = e.target.files?.[0]; if (f) uploadAsset("template_journal", f); }} /><div className="text-xs text-slate-400 mt-1">Current: {form.journalTemplateUrl || "Not uploaded"}</div></div>
          </div>
        </section>

        <section className="card space-y-4">
          <h2 className="text-lg font-semibold text-white">Document Numbering Templates</h2>
          <p className="text-sm text-slate-400">Define prefixes and next sequence values used by all ERP documents.</p>
          <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">
            <div className="form-group"><label className="label">Quote Prefix</label><input className="input" value={form.quoteNumberPrefix} onChange={(e) => setValue("quoteNumberPrefix", e.target.value)} /></div>
            <div className="form-group"><label className="label">Quote Next Seq</label><input type="number" min="1" className="input" value={form.quoteSequence} onChange={(e) => setValue("quoteSequence", Number(e.target.value || 1))} /></div>
            <div className="form-group"><label className="label">Order Prefix</label><input className="input" value={form.orderNumberPrefix} onChange={(e) => setValue("orderNumberPrefix", e.target.value)} /></div>
            <div className="form-group"><label className="label">Order Next Seq</label><input type="number" min="1" className="input" value={form.orderSequence} onChange={(e) => setValue("orderSequence", Number(e.target.value || 1))} /></div>
            <div className="form-group"><label className="label">Invoice Prefix</label><input className="input" value={form.invoiceNumberPrefix} onChange={(e) => setValue("invoiceNumberPrefix", e.target.value)} /></div>
            <div className="form-group"><label className="label">Invoice Next Seq</label><input type="number" min="1" className="input" value={form.invoiceSequence} onChange={(e) => setValue("invoiceSequence", Number(e.target.value || 1))} /></div>
            <div className="form-group"><label className="label">Delivery Prefix</label><input className="input" value={form.deliveryNumberPrefix} onChange={(e) => setValue("deliveryNumberPrefix", e.target.value)} /></div>
            <div className="form-group"><label className="label">Delivery Next Seq</label><input type="number" min="1" className="input" value={form.deliverySequence} onChange={(e) => setValue("deliverySequence", Number(e.target.value || 1))} /></div>
            <div className="form-group"><label className="label">PO Prefix</label><input className="input" value={form.purchaseOrderNumberPrefix} onChange={(e) => setValue("purchaseOrderNumberPrefix", e.target.value)} /></div>
            <div className="form-group"><label className="label">PO Next Seq</label><input type="number" min="1" className="input" value={form.purchaseOrderSequence} onChange={(e) => setValue("purchaseOrderSequence", Number(e.target.value || 1))} /></div>
            <div className="form-group"><label className="label">Journal Prefix</label><input className="input" value={form.journalNumberPrefix} onChange={(e) => setValue("journalNumberPrefix", e.target.value)} /></div>
            <div className="form-group"><label className="label">Journal Next Seq</label><input type="number" min="1" className="input" value={form.journalSequence} onChange={(e) => setValue("journalSequence", Number(e.target.value || 1))} /></div>
            <div className="form-group"><label className="label">Payroll Prefix</label><input className="input" value={form.payrollNumberPrefix} onChange={(e) => setValue("payrollNumberPrefix", e.target.value)} /></div>
            <div className="form-group"><label className="label">Payroll Next Seq</label><input type="number" min="1" className="input" value={form.payrollSequence} onChange={(e) => setValue("payrollSequence", Number(e.target.value || 1))} /></div>
          </div>
        </section>

        {loading && <div className="alert-info">Loading company settings...</div>}
        <NavOrderSection />
        {uploadingAsset && <div className="alert-info">Uploading {uploadingAsset} image...</div>}
        {message && <div className="alert-success">{message}</div>}
        {error && <div className="alert-error">{error}</div>}

        <div className="flex flex-wrap gap-3">
          <button type="submit" className="btn-primary" disabled={saving || loading}>
            {saving ? "Saving..." : "Save Settings"}
          </button>
          <button
            type="button"
            className="btn-secondary"
            onClick={() => window.location.reload()}
            disabled={saving}
          >
            Reload
          </button>
        </div>
      </form>
    </main>
  );
}
